--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-16-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "SUBJECT" 
   (	"CODE" NUMBER, 
	"MAJOR" VARCHAR2(30 BYTE), 
	"DIVISION" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER, 
	"SUB" VARCHAR2(80 BYTE), 
	"CREDIT" NUMBER, 
	"PROFESSOR" VARCHAR2(15 BYTE), 
	"TIMES" VARCHAR2(10 BYTE), 
	"ROOM" VARCHAR2(30 BYTE), 
	"CNT" NUMBER, 
	"CHECKED" VARCHAR2(20 BYTE), 
	"SEMESTER" NUMBER, 
	"S_GRADE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SUBJECT"."CODE" IS '과목코드';
 
   COMMENT ON COLUMN "SUBJECT"."MAJOR" IS '학과';
 
   COMMENT ON COLUMN "SUBJECT"."DIVISION" IS '전공,교양';
 
   COMMENT ON COLUMN "SUBJECT"."YEAR" IS '개설년도';
 
   COMMENT ON COLUMN "SUBJECT"."SUB" IS '과목명';
 
   COMMENT ON COLUMN "SUBJECT"."CREDIT" IS '학점';
 
   COMMENT ON COLUMN "SUBJECT"."PROFESSOR" IS '교수';
 
   COMMENT ON COLUMN "SUBJECT"."TIMES" IS '강의시간';
 
   COMMENT ON COLUMN "SUBJECT"."ROOM" IS '강의실';
 
   COMMENT ON COLUMN "SUBJECT"."CNT" IS '수강인원';
 
   COMMENT ON COLUMN "SUBJECT"."CHECKED" IS '처리상태';
 
   COMMENT ON COLUMN "SUBJECT"."SEMESTER" IS '학기';
 
   COMMENT ON COLUMN "SUBJECT"."S_GRADE" IS '학년';
--REM INSERTING into SUBJECT
--SET DEFINE OFF;
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (42,'컴퓨터학과','전공',2017,'nodejs',3,'이여섯','수/5-8','이노플렉스',60,'처리완료',1,null);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (41,'컴퓨터학과','교양',2017,'ㅁㄴㅇㅁㄴㅇㅁㄴㅇ',2,'이여섯','월/1-1','ㅁㄴㅇㅁㄴㅇ',30,'처리완료',1,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (46,'컴퓨터학과','전공',2017,'spring11',3,'이여섯','월/3-7','aaa',30,'처리중',1,null);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (1,'컴퓨터학과','전공',2016,'C',3,'이여섯','금/2-8','공학관/203',1,'처리완료',2,1);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (2,'컴퓨터학과','전공',2016,'C++',3,'이여섯','월/4-7','공학관/208',2,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (3,'컴퓨터학과','전공',2015,'JAVA',3,'김넷','화/5-8','공학관/209',1,'처리완료',2,3);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (4,'문학','교양',2016,'글쓰기',2,'이일곱','금/1-2','경영학관/304',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (5,'문학','교양',2015,'말하기',3,'김넷','금/1-2','경영학관/404',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (6,'컴퓨터학과','전공',2016,'Android',3,'이여섯','목/4-7','공학관/301',1,'처리완료',2,1);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (7,'문학','교양',2016,'시쓰기',2,'최하나','목/2-3','상경학관/302',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (8,'멀티미디어학과','전공',2014,'포토샵',3,'최하나','목/1-4','광학관/401',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (9,'문학','교양',2014,'소설쓰기',3,'이일곱','금/7-8','상경학관/303',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (10,'멀티미디어학과','전공',2016,'플래시',3,'이다섯','화/1-4','공학관/402',1,'처리완료',2,3);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (16,'컴퓨터학과','전공',2016,'spring',3,'이여섯','수/2-8','208호',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (18,'컴퓨터학과','전공',2016,'과아목',3,'이여섯','목/2-8','길바닥',1,'처리완료',2,3);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (19,'컴퓨터학과','전공',2016,'JAVA',3,'이여섯','화/4-7','우리집',1,'처리완료',2,3);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (20,'컴퓨터학과','전공',2016,'과목',3,'이여섯','토/1-2','코스타',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (32,'컴퓨터학과','전공',2016,'가가가가가각',3,'이여섯','월/2-2','asdasd',1,'처리완료',2,1);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (17,'컴퓨터학과','전공',2016,'봄',3,'이여섯','금/3-5','...',1,'처리완료',2,4);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (45,'컴퓨터학과','교양',2017,'dddd',2,'이여섯','화/1-4','dddd',30,'처리완료',1,null);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (13,'컴퓨터학과','전공',2016,'과목',3,'이여섯','월/1-6','어디',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (31,'컴퓨터학과','전공',2016,'XML',3,'이여섯','월/2-3','가디',1,'처리완료',2,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (11,'컴퓨터학과','전공',2016,'과목',3,'이여섯','토/1-5','here',1,'처리완료',2,4);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (12,'컴퓨터학과','전공',2016,'과목',3,'이여섯','토/1-8','여기...',1,'처리완료',1,1);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (14,'컴퓨터학과','전공',2016,'과목',3,'이여섯','월/1-2','206호',1,'처리완료',1,3);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (15,'컴퓨터학과','교양',2016,'과목명',2,'이여섯','토/2-5','207호',1,'처리완료',1,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (40,'컴퓨터학과','교양',2017,'ㅁ',2,'이여섯','월/1-1','ㅁ',30,'처리완료',1,1);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (23,'컴퓨터학과','전공',2017,'과목등록',2,'이여섯','월/1-7','ㅇ',1,'처리완료',1,4);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (30,'컴퓨터학과','전공',2017,'HTML',3,'이여섯','화/3-6','이노플렉스',1,'처리완료',1,2);
Insert into SUBJECT (CODE,MAJOR,DIVISION,YEAR,SUB,CREDIT,PROFESSOR,TIMES,ROOM,CNT,CHECKED,SEMESTER,S_GRADE) values (44,'컴퓨터학과','전공',2017,'ㅋㅋㅋㅋㅋㅋㅋㅋ',2,'이여섯','월/1-4','ㅋㅋㅋㅋㅋㅋㅋㅋㅋ',30,'처리완료',1,null);
--------------------------------------------------------
--  DDL for Index SYS_C0011850
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0011850" ON "SUBJECT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "SUBJECT" ADD CONSTRAINT "SUBJECT_CHK1" CHECK ("SEMESTER"=1 OR "SEMESTER"=2) ENABLE;
 
  ALTER TABLE "SUBJECT" MODIFY ("MAJOR" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("SUB" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("CREDIT" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("PROFESSOR" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("TIMES" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("ROOM" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" MODIFY ("CNT" NOT NULL ENABLE);
 
  ALTER TABLE "SUBJECT" ADD PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
